auto/urls.py
from django.urls import path
from . import views
from .views import AutoListView, MotoListView
urlpatterns = [
    path('new_ad/', views.new_ad, name='new_ad'),
    path('new_ad_moto/', views.new_ad_moto, name='new_ad_moto'),
    # path('auto/', views.auto, name='auto'),
    path('auto', AutoListView.as_view(), name='auto'),
    path('auto/<int:pk>', views.auto_details, name='auto_details'),
    path('auto/<int:pk>/delete', views.delete_auto, name='delete_auto'),
    path('auto/<int:pk>/share/', views.auto_share, name='auto_share'),
    path('auto/search/', views.auto_search, name='auto_search'),
    # path('moto/', views.moto, name='moto'),
    path('moto', MotoListView.as_view(), name='moto'),
    path('moto/<int:pk>', views.moto_details, name='moto_details'),
    path('moto/<int:pk>/delete', views.delete_moto, name='delete_moto'),
    path('a_filters/', views.auto_filter, name='auto_filters'),
    path('m_filters/', views.moto_filter, name='moto_filters'),
    path('auto/<int:pk>/mark', views.auto_bookmark, name='auto_bookmark'),
    path('a_bookmarks/', views.auto_bookmarks, name='a_bookmarks'),
    path('moto/<int:pk>/mark', views.moto_bookmark, name='moto_bookmark'),
    path('m_bookmarks/', views.moto_bookmarks, name='m_bookmarks'),
    path('all_reviews', views.all_reviews, name='reviews'),
    path('auto/<int:pk>/create/', views.auto_create_review, name='auto_create_review'),
    path('moto/<int:pk>/create/', views.moto_create_review, name='moto_create_review'),
    path('auto/<int:pk>/rew_about_this_car/', views.all_rew_about_this_car, name='all_rew_about_this_car'),
    path('moto/<int:pk>/rew_about_this_motor/', views.all_rew_about_this_motor, name='all_rew_about_this_motor'),
    path('rew_about_this_car/<int:pk>/', views.a_rev_details, name='a_rev_details'),
    path('rew_about_this_motor/<int:pk>/', views.m_rev_details, name='m_rev_details'),
    path('rew_about_this_car/<int:pk>/delete', views.a_rev_delete, name='a_rev_delete'),
    path('rew_about_this_motor/<int:pk>/delete', views.m_rev_delete, name='m_rev_delete'),

]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [url(r'^$', views.cart_detail, name='cart_detail'),
               url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
               url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove,
                   name='cart_remove'),
               ]

catalog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from .views import category_list, subcategory_list, product_list, product_detail

namespace = 'catalog'
appname = 'catalog'

# urlpatterns = [
#     url(r'^$', views.category_list, name='category_list'),
#     url(r'^(?P<category_slug>[-\w]+)/$', views.subcategory_list, name='subcategory_list'),
#     url(r'^(?P<category_slug>[-\w]+)/(?P<subcategory_slug>[-\w]+)/$', views.product_list, name='product_list'),
#     url(r'^(?P<id>\d+)/$', views.product_detail,name='product_detail'),
# ]
urlpatterns = [
    path('', views.category_list, name='category_list'),
    path('<slug:category_slug>/', views.subcategory_list, name='subcategory_list'),
    path('<slug:category_slug>/<slug:subcategory_slug>/', views.product_list, name='product_list'),
    path('<slug:category_slug>/<slug:subcategory_slug>/<slug:slug>/', views.product_detail,
         name='product_detail'),

]

# urlpatterns = [
#     url(r'^', views.category_list, name='category_list'),
#     url(r'^(?P<category_slug>[-\w]+)/$', views.subcategory_list, name='subcategory_list'),
#     url(r'^(?P<subcategory_slug>[-\w]+)/$', views.product_list, name='product_list'),
#     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
# ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from . import settings
# from news.views import index, home_view
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    path('', include('index.urls')),
    path('', include("news.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
    url(r'^catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^news/', include(('news.urls', 'news'), namespace='news')),
    url(r'^ab/', include(('auto.urls', 'ab'), namespace='ab')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls', namespace='payment')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

index/templates/base.html
<html>
<head>
    <title>Simple Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/tagsinput.css"/>
    <link rel="shortcut icon" href="media/favicon.ico" type="image/x-icon">
    <link rel="icon" href="media/favicon.ico" type="image/x-icon">
    <script src="https://js.braintreegateway.com/web/3.44.2/js/client.min.js"></script>
    <script src="/static/js/hosted-fields.min.js"></script>
    <script src="//code-ya.jivosite.com/widget/dCcEKC8PkA" async></script>
    {% load thumbnail %}

</head>

<body>
<header>
    <div class="header">
        <div class="top-block">
            <div class="after-top-menu">
                <div class="top-menu">
                    <div class="top-element col-7">
                        <nav class="navigation col-12">
                            <ul>
                                <li><a class="navigation_link" href="{% url 'catalog:category_list' %}">Каталог</a></li>
                                <li><a class="navigation_link" href="/news/">Новости</a></li>
                                <li><a class="navigation_link" href="{% url 'ab:auto' %}">Автобарахолка</a></li>
                                <li><a class="navigation_link" href="{% url 'catalog:category_list' %}">Дома и
                                    квартиры</a>
                                </li>
                                <li><a class="navigation_link" href="{% url 'catalog:category_list' %}">Услуги</a></li>
                                <li><a class="navigation_link" href="{% url 'catalog:category_list' %}">Барахолка</a>
                                </li>
                                <li><a class="navigation_link" href="{% url 'catalog:category_list' %}">Форум</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="top-element col-4">
                        <div class="box">
                            <div class="currency">
                                {% for cur in currens %}
                                    {% if cur.Cur_Abbreviation == "USD" %}
                                        <p> ${{ cur.Cur_OfficialRate }}</p>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <article class="media">
                                <div class="media-left">
                                    <figure class="image is-50x50">
                                        <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image">
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <div>
                                        <p>
                                            <br>
                                            <span class="title">{{ weather.city }}</span>
                                            <span class="subtitle">{{ weather.temperature }}° C</span>
                                            {#                                            <br> {{ weather.description }}#}
                                        </p>
                                    </div>
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </div>
            <div class="top-action">
                <div class="top-action-elem col-8">
                    <div class="top-action-logo">
                        <a href="/"><img src="/media/logo.png" height="45px" width="180px"></a>
                    </div>
                </div>
                <div class="top-action-elem col-4">
                    <div class="personal">
                        {% if user.is_authenticated %}
                            <p>Привет {{ user.username }}!</p>
                        <a href="{% url 'cart:cart_detail' %}">Корзина</a>
                            <p><a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a></p>
                        {% else %}
                            <a href="{% url 'login' %}?next={{ request.path }}">Войти</a>
                        {% endif %}
                        <div class="cart">
                            {% with total_items=cart|length %}
                                {% if cart|length > 0 %}
                                    Ваша корзина:
                                    <a href="{% url 'cart:cart_detail' %}">
                                        {{ total_items }} item{{ total_items|pluralize }},
                                        {{ cart.get_total_price }} BYN
                                    </a>
                                {% else %}
                                    Ваша корзина пуста :-(
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</header>


<main>
    <div class="content">
        {% block content %}{% endblock content %}
    </div>
</main>
<footer>
    <div class="footer">
        <div class="g-bottom-i">
            <div class="footer-style">
                <div class="footer-style__flex">
                    <div class="footer-style__part footer-style__part_1">
                        <ul class="footer-style__list">
                            <li class="footer-style__item">
                                <a href="https://blog.onliner.by/about"
                                   class="footer-style__link footer-style__link_primary">
                                    О компании
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://people.onliner.by/contacts"
                                   class="footer-style__link footer-style__link_primary">
                                    Контакты редакции
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://b2breg.onliner.by/advertising"
                                   class="footer-style__link footer-style__link_additional">
                                    Реклама
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://docs.google.com/spreadsheets/d/1SGFaTkV_Ru4vI29ml9yvR-dMz9rOl7DVVpKk64w5lqM/edit#gid=372016392"
                                   class="footer-style__link footer-style__link_additional">
                                    Размещение в каталоге
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://blog.onliner.by/vacancy"
                                   class="footer-style__link footer-style__link_primary">
                                    Вакансии
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://blog.onliner.by/manifest"
                                   class="footer-style__link footer-style__link_primary">
                                    Манифест
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://blog.onliner.by/siterules"
                                   class="footer-style__link footer-style__link_primary">
                                    Пользовательское соглашение
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://blog.onliner.by/publichnye-dogovory"
                                   class="footer-style__link footer-style__link_primary">
                                    Публичные договоры
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://blog.onliner.by/politika-konfidencialnosti"
                                   class="footer-style__link footer-style__link_primary">
                                    Политика конфиденциальности
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://support.onliner.by/"
                                   class="footer-style__link footer-style__link_primary">
                                    Поддержка пользователей
                                </a>
                            </li>
                            <li class="footer-style__item">
                                <a href="https://blog.onliner.by/pravila-vozvrata-tovarov-i-deneg"
                                   class="footer-style__link footer-style__link_primary">
                                    Правила возврата
                                </a>
                            </li>
                        </ul>
                        <div class="footer-style__social">
                            <a href="https://vk.com/onliner" rel="noopener" target="_blank"
                               class="footer-style__social-button footer-style__social-button_vk"></a>
                            <a href="https://facebook.com/onlinerby" rel="noopener" target="_blank"
                               class="footer-style__social-button footer-style__social-button_fb"></a>
                            <a href="https://twitter.com/OnlinerBY" rel="noopener" target="_blank"
                               class="footer-style__social-button footer-style__social-button_tw"></a>
                            <a href="https://youtube.com/onlinerby" rel="noopener" target="_blank"
                               class="footer-style__social-button footer-style__social-button_yt"></a>
                        </div>
                    </div>
                    <div class="footer-style__part footer-style__part_2">
                        <div class="footer-style__logo"></div>
                        <div class="footer-style__copy">
                            © 2001—2021 Onlíner
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="/static/js/tagsinput.js"></script>
<script>
    $("#post-form").submit(function (e) {
        e.preventDefault();
    });</script>
</body>
</html>

index/templates/currency.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-5">
        <div>
            {% for cur in currens %}
                <p> {{ cur.Cur_Scale }} {{ cur.Cur_Name}} = {{ cur.Cur_OfficialRate }} BYN  {{ cur.date}}</p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

index/templates/index.html
{% extends 'base.html' %}

{% block content %}
<!--    <marquee height="40px" scrollamount="1" behavior="scroll" loop="infinite" bgcolor="white" vspace="6">-->
<!--    <p style="color: black; font-style: oblique;" >-->
<!--        <img height="40" width="40" src="/media/photos/virus.jpg">Количество зараженных: {{stat.get_infected}} человек-->
<!--        <img height="40" width="40" src="/media/photos/death.jpg">Смертельные случаи: {{stat.get_deaths}} человек-->
<!--        <img height="40" width="40" src="/media/photos/recovered.jpg">Выздоровевшие: {{stat.get_recovered}} человек-->
<!--        <img height="40" width="40" src="/media/photos/sick.jpg">Сейчас болеют: {{stat.get_sick_now}} человек-->
<!--        <img height="40" width="40" src="/media/photos/test.jpg">Сделано тестов: {{stat.get_tests_done}} штук</p>-->
<!--    </marquee>-->
    <div class="container pt-5">
        <div>
            {% for cat in categories %}
                <div>
                    <div>
                        <h3><a href="news/{{ cat.slug }}">{{ cat.title }}</a></h3>
                    </div>
                    <div class="col-md-12 category_news">
                                            {% for post in posts %}
                                                {% if post.category_id == cat.id %}
                                                <div class="col-md-4">
                                                <div class="cards">
                                                    <div class="row no-gutters flex-md-row mb-4 shadow-sm h-md-250"
                                                         style="background-image: url('{{ post.picture.avatar.url }}');background-size:cover">
                                                        <div class="col p-4 d-flex news_block">
                                                            <a class="news_items" href="{% url 'detail' post.slug %} ">
                                                                <h3 class="my-1">{{ post.title }}</h3></a>
                                                        </div>
                                                    </div>
                                                </div>
                                                </div>
                                                {% endif %}
                                            {% endfor %}
                    </div>
                        {% for cur in currens %}
                        <p> {{ cur.Cur_Name}} = {{ cur.Cur_OfficialRate }} </p>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>


        {#        {% for car in five_auto %}#}
        {#            <a href="{% url 'auto' %}">{{ car }}</a>#}
        {#        {% endfor %}#}

        {#            {% for cat in categories %}#}
        {#                <div class="row mb-2 posts">#}
        {#                <h3 class="my-1"><a href="news/post/{{ cat.slug }}" >{{ cat.title }}</a></h3>#}
        {#                {% for post in posts %}#}
        {##}
        {#                <div class="col-md-6">#}
        {#                    <div class="cards">#}
        {#                        <div class="row no-gutters flex-md-row mb-4 shadow-sm h-md-250"#}
        {#                             style="background-image: url('{{ post.picture.avatar.url }}');background-size:cover">#}
        {#                            <div class="col p-4 d-flex news_block">#}
        {#                                <a class="news_items" href="{% url 'detail' post.slug %} ">#}
        {#                                    <h3 class="my-1">{{ post.title }}</h3></a>#}
        {#                            </div>#}
        {#                        </div>#}
        {#                    </div>#}
        {#                </div>#}
        {#                </div>#}
        {#                {% endfor %}#}
        {##}
        {#            {% endfor %}#}
        {#        </div>#}
        {#        <div>#}
        {#        </div>#}

    </div>
{% endblock content %}