auto/urls.py
from django.urls import path
from . import views
from .views import AutoListView, MotoListView
urlpatterns = [
    path('new_ad/', views.new_ad, name='new_ad'),
    path('new_ad_moto/', views.new_ad_moto, name='new_ad_moto'),
    # path('auto/', views.auto, name='auto'),
    path('auto', AutoListView.as_view(), name='auto'),
    path('auto/<int:pk>', views.auto_details, name='auto_details'),
    path('auto/<int:pk>/delete', views.delete_auto, name='delete_auto'),
    path('auto/<int:pk>/share/', views.auto_share, name='auto_share'),
    path('auto/search/', views.auto_search, name='auto_search'),
    # path('moto/', views.moto, name='moto'),
    path('moto', MotoListView.as_view(), name='moto'),
    path('moto/<int:pk>', views.moto_details, name='moto_details'),
    path('moto/<int:pk>/delete', views.delete_moto, name='delete_moto'),
    path('a_filters/', views.auto_filter, name='auto_filters'),
    path('m_filters/', views.moto_filter, name='moto_filters'),
    path('auto/<int:pk>/mark', views.auto_bookmark, name='auto_bookmark'),
    path('a_bookmarks/', views.auto_bookmarks, name='a_bookmarks'),
    path('moto/<int:pk>/mark', views.moto_bookmark, name='moto_bookmark'),
    path('m_bookmarks/', views.moto_bookmarks, name='m_bookmarks'),
    path('all_reviews', views.all_reviews, name='reviews'),
    path('auto/<int:pk>/create/', views.auto_create_review, name='auto_create_review'),
    path('moto/<int:pk>/create/', views.moto_create_review, name='moto_create_review'),
    path('auto/<int:pk>/rew_about_this_car/', views.all_rew_about_this_car, name='all_rew_about_this_car'),
    path('moto/<int:pk>/rew_about_this_motor/', views.all_rew_about_this_motor, name='all_rew_about_this_motor'),
    path('rew_about_this_car/<int:pk>/', views.a_rev_details, name='a_rev_details'),
    path('rew_about_this_motor/<int:pk>/', views.m_rev_details, name='m_rev_details'),
    path('rew_about_this_car/<int:pk>/delete', views.a_rev_delete, name='a_rev_delete'),
    path('rew_about_this_motor/<int:pk>/delete', views.m_rev_delete, name='m_rev_delete'),

]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [url(r'^$', views.cart_detail, name='cart_detail'),
               url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
               url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove,
                   name='cart_remove'),
               ]

coupons/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^apply/$', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^history/$', views.history, name='history'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from . import settings
# from news.views import index, home_view
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    path('', include('index.urls')),
    path('', include("news.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
    url(r'^catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^news/', include(('news.urls', 'news'), namespace='news')),
    url(r'^ab/', include(('auto.urls', 'ab'), namespace='ab')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls', namespace='payment')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views.decorators.http import require_POST
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                            initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart_detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart_detail.html
{% extends "base.html" %}
{% load static %}
 
{% block title %}
    Your shopping cart
{% endblock %}
 
{% block content %}
    <h1>Ваша корзина покупок</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за единицу</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.slug }}">
                            <img src="
                                    {% if product.picture %}{{ product.icon.cat_icon.url }}{% else %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}"
                              method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
        <tr class="subtotal">
            <td>Цена</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        <tr>
            <td>
                Купон № {{ cart.coupon.code }}
                (скидка {{ cart.coupon.discount }}%)
            </td>
            <td colspan="4"></td>
            <td class="num neg">
                - ${{ cart.get_discount|floatformat:"2" }}
            </td>
        </tr>
    {% endif %}
    <tr class="total">
        <td>Цена с учетом купона</td>
        <td colspan="4"></td>
        <td class="num">
            ${{ cart.get_total_price_after_discount|floatformat:"2" }}
        </td>
    </tr>
        </tbody>
    </table>
    <form action="{% url 'coupons:apply' %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="/" class="button light">Продолжить покупки</a>
        <a href="{% url 'orders:order_create' %}" class="button">Купить</a>
    </p>
{% endblock %}