auto/urls.py
from django.urls import path
from . import views
from .views import AutoListView, MotoListView
urlpatterns = [
    path('new_ad/', views.new_ad, name='new_ad'),
    path('new_ad_moto/', views.new_ad_moto, name='new_ad_moto'),
    # path('auto/', views.auto, name='auto'),
    path('auto', AutoListView.as_view(), name='auto'),
    path('auto/<int:pk>', views.auto_details, name='auto_details'),
    path('auto/<int:pk>/delete', views.delete_auto, name='delete_auto'),
    path('auto/<int:pk>/share/', views.auto_share, name='auto_share'),
    path('auto/search/', views.auto_search, name='auto_search'),
    # path('moto/', views.moto, name='moto'),
    path('moto', MotoListView.as_view(), name='moto'),
    path('moto/<int:pk>', views.moto_details, name='moto_details'),
    path('moto/<int:pk>/delete', views.delete_moto, name='delete_moto'),
    path('a_filters/', views.auto_filter, name='auto_filters'),
    path('m_filters/', views.moto_filter, name='moto_filters'),
    path('auto/<int:pk>/mark', views.auto_bookmark, name='auto_bookmark'),
    path('a_bookmarks/', views.auto_bookmarks, name='a_bookmarks'),
    path('moto/<int:pk>/mark', views.moto_bookmark, name='moto_bookmark'),
    path('m_bookmarks/', views.moto_bookmarks, name='m_bookmarks'),
    path('all_reviews', views.all_reviews, name='reviews'),
    path('auto/<int:pk>/create/', views.auto_create_review, name='auto_create_review'),
    path('moto/<int:pk>/create/', views.moto_create_review, name='moto_create_review'),
    path('auto/<int:pk>/rew_about_this_car/', views.all_rew_about_this_car, name='all_rew_about_this_car'),
    path('moto/<int:pk>/rew_about_this_motor/', views.all_rew_about_this_motor, name='all_rew_about_this_motor'),
    path('rew_about_this_car/<int:pk>/', views.a_rev_details, name='a_rev_details'),
    path('rew_about_this_motor/<int:pk>/', views.m_rev_details, name='m_rev_details'),
    path('rew_about_this_car/<int:pk>/delete', views.a_rev_delete, name='a_rev_delete'),
    path('rew_about_this_motor/<int:pk>/delete', views.m_rev_delete, name='m_rev_delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from . import settings
# from news.views import index, home_view
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    path('', include('index.urls')),
    path('', include("news.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
    url(r'^catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^news/', include(('news.urls', 'news'), namespace='news')),
    url(r'^ab/', include(('auto.urls', 'ab'), namespace='ab')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls', namespace='payment')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auto/forms.py
from django import forms
from .models import *


class PostAutoForm(forms.ModelForm):
    class Meta:
        model = Auto
        exclude = ("published_date",)
        widgets = {
            'brand': forms.Select(choices=brand_choice),
            'model': forms.Select(choices=models_choice),
            'type_of_body': forms.TextInput(),
            'transmission': forms.TextInput(),
            'drive_unit': forms.TextInput(),
            'type_of_fuel': forms.TextInput(),
            'year': forms.TextInput(),
            'location': forms.TextInput(),
            'mileage': forms.TextInput(),
            'engine_capacity': forms.TextInput(),
            'description': forms.Textarea(),
            'price': forms.TextInput(),
            'pictures': forms.FileInput(),
        }

    # def __init__(self, *args, **kwargs):
    #     super(PostAutoForm, self).__init__(*args, **kwargs)
    #     for field in iter(self.fields):
    #         self.fields[field].widget.attrs.update({
    #             'class': 'form-control'
    #         })


class PostMotoForm(forms.ModelForm):
    class Meta:
        model = Moto
        exclude = ("published_date",)
        widgets = {

            'brand': forms.TextInput(),
            'model': forms.TextInput(),
            'year': forms.TextInput(),
            'location': forms.TextInput(),
            'mileage': forms.TextInput(),
            'engine_capacity': forms.TextInput(),
            'description': forms.Textarea(),
            'price': forms.TextInput(),
            'pictures': forms.FileInput(),
        }

    # def __init__(self, *args, **kwargs):
    #     super(PostMotoForm, self).__init__(*args, **kwargs)
    #     for field in iter(self.fields):
    #         self.fields[field].widget.attrs.update({
    #             'class': 'form-control'
    #         })


class AutoReviewForm(forms.ModelForm):
    class Meta:
        model = AutoReviews
        fields = ('rate', 'text',)
        widgets = {
            'rate': forms.RadioSelect(attrs={'class': 'inline'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Твой отзыв'})
        }

    # def __init__(self, *args, **kwargs):
    #     super(AutoReviewForm, self).__init__(*args, **kwargs)
    #     self.fields['rate'].label = 'Рейтинг'
    #     self.fields['text'].label = 'Отзыв'


class MotoReviewForm(forms.ModelForm):
    class Meta:
        model = MotoReviews
        fields = ('rate', 'text',)
        widgets = {
            'rate': forms.RadioSelect(attrs={'class': 'inline'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Твой отзыв', 'name': 'kjlf'})
        }

    # def __init__(self, *args, **kwargs):
    #     super(MotoReviewForm, self).__init__(*args, **kwargs)
    #     self.fields['rate'].label = 'Рейтинг'
    #     self.fields['text'].label = 'Отзыв'


# def __init__(self, *args, **kwargs):
#     super(AutoReviewForm, self).__init__(*args, **kwargs)
#     self.fields['reviewed'].initial = Auto.objects.all().last()


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='Имя', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Ваше Имя'}))
    email = forms.EmailField(label='От кого', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Email отправителя'}))
    to = forms.EmailField(label='Кому', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Email получателя'}))
    comments = forms.CharField(required=False, label='Сообщение', widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Твой комментарий'}))


class SearchForm(forms.Form):
    query = forms.CharField()
    #
    # def __init__(self, *args, **kwargs):
    #     super(SearchForm, self).__init__(*args, **kwargs)
    #     self.fields['query'].label = 'Ваш запрос'

auto/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import PostAutoForm, PostMotoForm, AutoReviewForm, MotoReviewForm, EmailPostForm, SearchForm
from django.utils import timezone
from .filters import AutoFilter, MotoFilter
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
#from django.contrib.postgres.search import SearchVector


def auto_share(request, pk):
    car = get_object_or_404(Auto, pk=pk)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            auto_url = request.build_absolute_uri(car.get_absolute_url())
            subject = f"{cd['name']} Рекомендует взглянуть на эту тачку" \
                      f"{car.brand} - {car.model}"
            message = f"Смотри {car.brand} - {car.model} по ссылке {auto_url}\n\n" \
                      f"Комментарий от {cd['name']}: {cd['comments']}"
            send_mail(subject, message, 'ibahutski@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'car': car,
        'form': form,
        'sent': sent,
    }
    return render(request, 'auto_share.html', context)


class AutoListView(ListView):
    queryset = Auto.objects.all().order_by('published_date')[::-1]
    context_object_name = 'cars'
    paginate_by = 2
    template_name = 'auto.html'


# def auto(request):
#     object_list = Auto.objects.all().order_by('published_date')[::-1]
#     paginator = Paginator(object_list, 2)  # 3 posts in each page
#     page = request.GET.get('page')
#     try:
#         cars = paginator.page(page)
#     except PageNotAnInteger:
#     # If page is not an integer deliver the first page
#         cars = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page
#         cars = paginator.page(paginator.num_pages)
#     context = {
#         'cars': cars,
#         'page': page
#     }
#     return render(request, 'auto.html', context)


def auto_details(request, pk):
    car = get_object_or_404(Auto, pk=pk)
    queryset = UserAutoMarks.objects.filter(user=request.user, auto=car).first()
    context = {
        'car': car,
        'queryset': queryset,
    }
    return render(request, 'auto_details.html', context)


def delete_auto(request, pk):
    car = get_object_or_404(Auto, pk=pk)
    car.delete()
    return redirect('ab:auto')


def auto_filter(request):
    a_filter = AutoFilter(request.GET, queryset=Auto.objects.all().order_by('published_date').reverse())
    context = {
        'a_filter': a_filter,
    }
    return render(request, 'auto_filters.html', context)


def moto_filter(request):
    m_filter = MotoFilter(request.GET, queryset=Moto.objects.all().order_by('published_date').reverse())
    context = {
        'm_filter': m_filter,
    }
    return render(request, 'moto_filters.html', context)


class MotoListView(ListView):
    queryset = Moto.objects.all().order_by('published_date')[::-1]
    context_object_name = 'motors'
    paginate_by = 2
    template_name = 'moto.html'


# def moto(request):
#     object_list = Moto.objects.all().order_by('published_date')[::-1]
#     paginator = Paginator(object_list, 2)  # 3 posts in each page
#     page = request.GET.get('page')
#     try:
#         motors = paginator.page(page)
#     except PageNotAnInteger:
#     # If page is not an integer deliver the first page
#         motors = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page
#         motors = paginator.page(paginator.num_pages)
#     context = {
#         'motors': motors,
#         'page': page
#     }
#     return render(request, 'moto.html', context)


def moto_details(request, pk):
    motor = get_object_or_404(Moto, pk=pk)
    return render(request, 'moto_details.html', {'motor': motor})


def delete_moto(request, pk):
    motor = get_object_or_404(Moto, pk=pk)
    motor.delete()
    return redirect('ab:moto')


def new_ad(request):
    if request.method == "POST":
        form = PostAutoForm(request.POST, request.FILES)
        if form.is_valid():
            car = form.save(commit=False)
            car.author = request.user
            car.published_date = timezone.now()
            form.save()
            return redirect('ab:auto')
    else:
        form = PostAutoForm()
    return render(request, 'new_ad.html', {'form': form})


def new_ad_moto(request):
    if request.method == "POST":
        form = PostMotoForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            form.save()
            return redirect('ab:moto')
    else:
        form = PostMotoForm()
    return render(request, 'new_ad.html', {'form': form})


def auto_bookmarks(request):
    cars = [i.auto for i in UserAutoMarks.objects.filter(user=request.user)]
    return render(request, 'a_bookmarks.html', {'cars': cars})


def auto_bookmark(request, pk):
    user = request.user
    car = get_object_or_404(Auto, pk=pk)
    queryset = UserAutoMarks.objects.filter(user=user, auto=car).first()
    if not queryset:
        UserAutoMarks.objects.create(user=user, auto=car, in_bookmarks=True)
    else:
        UserAutoMarks.objects.get(user=user, auto=car, in_bookmarks=True).delete()

    return redirect('ab:auto_details', pk=car.pk)


def moto_bookmarks(request):
    motors = [i.moto for i in UserMotoMarks.objects.filter(user=request.user)]
    return render(request, 'm_bookmarks.html', {'motors': motors})


def moto_bookmark(request, pk):
    user = request.user
    motor = get_object_or_404(Moto, pk=pk)
    if not UserMotoMarks.objects.filter(user=user, moto=motor).first():
        UserMotoMarks.objects.create(user=user, moto=motor, in_bookmarks=True)

    return render(request, 'moto_details.html', {'motor': motor})


def all_reviews(request):
    all_a_rew = [i for i in AutoReviews.objects.filter(author=request.user)[::-1]]
    all_m_rew = [i for i in MotoReviews.objects.filter(author=request.user)[::-1]]

    context = {
        'all_a_rew': all_a_rew,
        'all_m_rew': all_m_rew
    }
    return render(request, 'all_reviews.html', context)


def auto_create_review(request, pk):
    car = get_object_or_404(Auto, pk=pk)
    if request.method == "POST":
        form = AutoReviewForm(request.POST)
        if form.is_valid():
            rew = form.save(commit=False)
            rew.author = request.user
            rew.reviewed = car
            form.save()
            return redirect('ab:auto_details', pk=car.pk)
    else:
        form = AutoReviewForm()
    return render(request, 'create_review.html', {'form': form})


def a_rev_details(request, pk):
    rew = get_object_or_404(AutoReviews, pk=pk)
    return render(request, 'a_rev_details.html', {'rew': rew})


def a_rev_delete(request, pk):
    rew = get_object_or_404(AutoReviews, pk=pk)
    rew.delete()
    return redirect('ab:all_rew_about_this_car', pk=rew.reviewed.pk)


def all_rew_about_this_car(request, pk):
    pk_auto = get_object_or_404(Auto, pk=pk)
    all_rew_one_car = [i for i in AutoReviews.objects.filter(reviewed_id=pk_auto, author=request.user)[::-1]]
    context = {
        'all_rew_one_car': all_rew_one_car,
        'pk_auto': pk_auto,
    }
    return render(request, 'all_rew_about_car.html', context)


def moto_create_review(request, pk):
    motor = get_object_or_404(Moto, pk=pk)
    if request.method == "POST":
        form = MotoReviewForm(request.POST)
        if form.is_valid():
            rew = form.save(commit=False)
            rew.author = request.user
            rew.reviewed = motor
            form.save()
            return redirect('ab:moto_details', pk=motor.pk)
    else:
        form = MotoReviewForm()
    return render(request, 'create_review.html', {'form': form})


def m_rev_details(request, pk):
    rew = get_object_or_404(MotoReviews, pk=pk)
    return render(request, 'm_rev_details.html', {'rew': rew})


def m_rev_delete(request, pk):
    rew = get_object_or_404(MotoReviews, pk=pk)
    rew.delete()
    return redirect('ab:all_rew_about_this_motor', pk=rew.reviewed.pk)


def all_rew_about_this_motor(request, pk):
    pk_moto = get_object_or_404(Moto, pk=pk)
    all_rew_one_motor = [i for i in MotoReviews.objects.filter(reviewed_id=pk_moto, author=request.user)[::-1]]
    context = {
        'all_rew_one_motor': all_rew_one_motor,
        'pk_moto': pk_moto,
    }
    return render(request, 'all_rew_about_motor.html', context)


def auto_search(request):
    # form = SearchForm()
    # query = None
    # results = []
    # if 'query' in request.GET:
    #     form = SearchForm(request.GET)
    # if form.is_valid():
    #     query = form.cleaned_data['query']
    #     results = Auto.objects.annotate(search=SearchVector('brand', 'model', 'year', 'location',),).filter(search=query)
    # context = {
    #     'form': form,
    #     'query': query,
    #     'results': results}
    # return render(request, 'search.html', context)
    return render (request, 'search.html')

auto/templates/auto.html
{% extends 'base.html' %}


{% block content %}
<div>
    <a class="btn btn-default" href="{% url 'ab:auto_filters' %}"
       style="border: 1px solid black; box-sizing: border-box;">Фильтры</a>
    <a class="btn btn-default" href="{% url 'ab:auto' %}" style="border: 1px solid black; box-sizing: border-box;">Автомобили</a>
    <a class="btn btn-default" href="{% url 'ab:moto' %}" style="border: 1px solid black; box-sizing: border-box;">Мотоциклы</a>
    <a class="btn btn-default" href="{% url 'ab:reviews' %}" style="border: 1px solid black; box-sizing: border-box;">Отзывы
        об авто</a>
    <a class="btn btn-default" href="#" style="border: 1px solid black; box-sizing: border-box;">Мои авто</a>
    <a class="btn btn-default" href="{% url 'ab:a_bookmarks' %}"
       style="border: 1px solid black; box-sizing: border-box;">Закладки</a>
    <a class="btn btn-default" href="{% url 'ab:new_ad' %}" style="border: 1px solid black; box-sizing: border-box;">Разместить
        объявление</a>
    <a href="{% url 'ab:auto_search' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search"
             viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>
    </a>
</div>
<div>
    <h1>Автобарахолка</h1>
    <div class="auto_full">
    {% for car in cars %}
            <div class="col-md-6">


    <img style="height: 400px; width: 600px" src="{{ car.pictures.url }}" alt=""/>
    <h1>Brand: {{car.brand}}</h1>
    <h1>Model: {{car.model}}</h1>
    <h1>Transmission: {{car.transmission}}</h1>
    <h1>Drive unit: {{car.drive_unit}}</h1>
    <h1>Type of fuel: {{car.type_of_fuel}}</h1>
    <h1>Type of body: {{car.type_of_body}}</h1>
    <h1>Year: {{car.year}}</h1>
    <h1>Location: {{car.location}}</h1>
    <a class="btn btn-warning btn-block" href="{% url 'ab:auto_details' pk=car.pk %}">Show more</a>
             </div>
    {% empty %}
    <div style="text-align: center">
        <p>Нет авто</p>
        <a href="/"><img src="/media/photos/upset.jpg" height="200px" width="200px"></a>
    </div>

    {% endfor %}
    </div>
</div>
<!--{% include "pagination.html" with page=cars %}-->
{% include "pagination.html" with page=page_obj %}

{% endblock content %}

auto/templates/auto_details.html
{% extends 'base.html' %}


{% block content %}
<div>
    <a class="btn btn-default" href="{% url 'ab:auto' %}" style="border: 1px solid black; box-sizing: border-box;">Автомобили</a>
    <a class="btn btn-default" href="{% url 'ab:moto' %}" style="border: 1px solid black; box-sizing: border-box;">Мотоциклы</a>
    <a class="btn btn-default" href="{% url 'ab:new_ad' %}" style="border: 1px solid black; box-sizing: border-box;">Разместить
        объявление</a>
    {% if user.is_authenticated %}
    {% if not queryset %}
    <a class="btn btn-default" href="{% url 'ab:auto_bookmark' pk=car.pk %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-star"
             viewBox="0 0 16 16">
            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
        </svg>
    </a>
    {% else %}
    <a class="btn btn-default" href="{% url 'ab:auto_bookmark' pk=car.pk %}">

        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-star-fill"
             viewBox="0 0 16 16">
            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
        </svg>
    </a>
    {% endif%}
    <a class="btn btn-default" href="{% url 'ab:all_rew_about_this_car' pk=car.pk %}"
       style="border: 1px solid black; box-sizing: border-box;">Отзывы об этом авто</a>
    {% endif %}
</div>
<a class="btn btn-danger" href="{% url 'ab:delete_auto' pk=car.pk %}">Delete</a>
<a class="btn btn-success" href="{% url 'ab:auto_share' pk=car.pk %}">Поделиться</a>


<img style="height: 400px; width: 600px" src="{{ car.pictures.url }}" alt=""/>
<h1>Brand: {{car.brand}}</h1>
<h1>Model: {{car.model}}</h1>
<h1>Transmission: {{car.transmission}}</h1>
<h1>Drive unit: {{car.drive_unit}}</h1>
<h1>Type of fuel: {{car.type_of_fuel}}</h1>
<h1>Type of body: {{car.type_of_body}}</h1>
<h1>Year: {{car.year}}</h1>
<h1>Location: {{car.location}}</h1>
<h1>Mileage: {{car.mileage}}</h1>
<h1>Price: {{car.price}}</h1>
<h1>Description: {{car.description}}</h1>
<div>
    <a class="btn btn-light" href="{% url 'ab:auto_create_review' pk=car.pk %}">Оставить отзыв:
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-award"
             viewBox="0 0 16 16">
            <path d="M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z"/>
            <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
        </svg>
    </a>
</div>

</div>
{% endblock %}

auto/templates/create_review.html
{% extends 'base.html' %}


{% block content %}
    <form  method="POST" class="form-group">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-primary">Разместить</button>
    </form>
{% endblock content %}

auto/templates/moto_details.html
{% extends 'base.html' %}

{% block content %}
<div>
    <a class="btn btn-default"  href="{% url 'ab:auto' %}" style="border: 1px solid black; box-sizing: border-box;">Автомобили</a>
    <a class="btn btn-default"  href="{% url 'ab:moto' %}" style="border: 1px solid black; box-sizing: border-box;">Мотоциклы</a>
    <a class="btn btn-default" href="{% url 'ab:new_ad_moto' %}" style="border: 1px solid black; box-sizing: border-box;">Разместить объявление</a>
    {% if user.is_authenticated %}
    <a class="btn btn-default" href="{% url 'ab:moto_bookmark' pk=motor.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16"><path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/></svg></a>
    <a class="btn btn-default" href="{% url 'ab:all_rew_about_this_motor' pk=motor.pk %}" style="border: 1px solid black; box-sizing: border-box;">Отзывы об этом мото</a>

    {% endif %}
</div>
<a class="btn btn-danger" href="{% url 'ab:delete_moto' pk=motor.pk %}">Delete</a>


    <img style="height: 400px; width: 600px" src="{{ motor.pictures.url }}" alt=""/>
    <h1>Model: {{motor.model}}</h1>
    <h1>Engine capacity: {{motor.engine_capacity}}</h1>
    <h1>Year: {{motor.year}}</h1>
    <h1>Location: {{motor.location}}</h1>
    <h1>Price: {{motor.price}}</h1>
    <h1>Description: {{motor.description}}</h1>
    <div>
        <a class="btn btn-light" href="{% url 'ab:moto_create_review' pk=motor.pk %}">Оставить отзыв:
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-award"
                 viewBox="0 0 16 16">
                <path d="M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z"/>
                <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
            </svg>
        </a>
    </div>

{% endblock content %}    